### ISSUE TITLE
how to add my own categories with my own icon images(png) as emojis. 

### ISSUE THREAD

**Issue by rboopathyAST** [puranjayjain/emojione-selector#4]
how to add my own categories with my own icon images(png) as emojis. 
how to avoid to load default icons

**Comment by puranjayjain** [comment]
@rboopathyAST  you can do so but would need to build the project on your own, you will have to change https://github.com/puranjayjain/emojione-selector/blob/master/emojione-selector.html#L562
to your own `categories.json` file and add your pngs over there.

**Comment by rboopathyAST** [comment]
Thank you very much for your response. I have already used that way, it is working good 👍

**Comment by puranjayjain** [comment]
Closing this issue then @rboopathyAST  👍
